### ISSUE TITLE
Not able to import CSV properly

### ISSUE THREAD

**Issue by BenMcD0nald** [EdisonPeM/strapi-plugin-import-export-content#15]
Hey,

Thanks for the work on this plugin. Having a bit of an issue though....

When I try to import from CSV I'm getting an error about the file type. The CSV I'm using is actually using a modified export so not sure what the issue is. I can however paste that same information as raw data and it's working just fine

Also, is it possible to put a feature on the roadmap that will merge existing records based on the id etc? I suppose the id might also need to be exported for that. If I figure out how to do it I'll mention but I'm still a newbie developer so a bit above my head at the moment...

**Comment by Sajakiari** [comment]
I've had the same issue with file import. The problem was that the MIME type of my file was `application/vnd.ms-excel` which I got by editing it with Excel. But the plugin accepts only `text/csv` MIME type for .csv files.

My solution was to copy the plugin's code, edit `admin/src/constants/formats.js`, and add Excel CSV MIME type there. 

```
const FORMATS = [
  { name: 'csv', mimeType: 'text/csv', ext: '.csv' },
  { name: 'csv', mimeType: 'application/vnd.ms-excel', ext: '.csv' },
  { name: 'json', mimeType: 'application/json', ext: '.json' },
];

export default FORMATS;
```

**Comment by EdisonPeM** [comment]
Thanks @Sajakiari for the idea.

This problem has already been solved by adding a new format of type **csv-excel** with the mimetype `application/vnd.ms-excel`
